# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  unittests:
    docker:
      - image: circleci/python:3.8.3
    
    steps:
      - checkout
      - run:
          name: virtualenv creation
          command: |
            pip install venv
            virtualenv venv
      - run:
          name: dependency installation
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: dependency output for debugging
          command: |        
            pip install pipdeptree
            pipdeptree
      - run:
          name: run tests
          command: |
            mkdir -p server-test-reports/pytest
            pipenv run pytest --cov=snps --cov-report xml:server-test-reports/coverage.xml --junitxml server-test-reports/pytest/tests.xml tests
            bash <(curl -s https://codecov.io/bash)
            pipenv run black --check --diff .
      - store_test_results:
          # must be a directory with named subdirectories
          path: server/server-test-reports
      - store_artifacts:
          path: server/server-test-reports
      - run:
          name: check linting
          command: |
            pipenv run black --check --diff .

workflows:
  test:
    jobs:
      - "unittests"